-- RESOURCE DESTRUCTION
USE ROLE SYSADMIN;
DROP WAREHOUSE IF EXISTS LEARNINGSNOWPARKVW;
DROP DATABASE IF EXISTS LEARNINGSNOWPARKDB;
DROP DATABASE IF EXISTS HOL_DB;

-- ROLE
USE ROLE SECURITYADMIN;
DROP ROLE IF EXISTS LEARNINGSNOWPARKROLE;
